apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Garante 2GB de espaço em disco para o banco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "database-role"
        vault.hashicorp.com/agent-inject-secret-db_pass: "secret/data/colegio-conecta/database"
        vault.hashicorp.com/agent-inject-template-db_pass: |
          {{- with secret "secret/data/colegio-conecta/database" -}}{{ .Data.data.password }}{{- end -}}
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi-srv5
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "regis"
            - name: POSTGRES_PASSWORD_FILE
              value: /vault/secrets/db_pass
            - name: POSTGRES_DB
              value: "lista_presenca"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432