apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colegioconecta-ingress
  namespace: default
  annotations:
    # Aciona a fábrica de certificados que acabamos de criar
    cert-manager.io/cluster-issuer: "emissor-local"
spec:
  ingressClassName: nginx # Especifica que queremos usar o controlador Nginx para este Ingress
  tls:
    - hosts:
      - colegioconecta.nprd.app
      # O cert-manager vai criar esse arquivo secret com a chave SSL automaticamente
      secretName: colegioconecta-tls
  rules:
  - host: colegioconecta.nprd.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Apontando para o nome exato do seu output
            name: frontend-service 
            port:
              # Usando a porta interna, por onde o Ingress vai rotear o tráfego
              number: 80
