apiVersion: apps/v1
kind: Deployment
metadata:
  name: lista-presenca-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        # Aqui é o local exato para o Vault ler
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "backend-role"
        vault.hashicorp.com/agent-inject-secret-database.properties: "secret/data/colegio-conecta/database"
        vault.hashicorp.com/agent-inject-template-database.properties: |
          {{- with secret "secret/data/colegio-conecta/database" -}}
          spring.datasource.password={{ .Data.data.password }}
          {{- end -}}
    spec:
      nodeSelector:
        hardware: pizero
      containers:
        - name: backend
          image: docker.io/reginaldoraraujo/lista-presenca-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /alunos
              port: 8080
            failureThreshold: 120    # Tenta 120 vezes antes de desistir
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 600
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "400m"
          env:
            - name: DB_URL
              value: "jdbc:postgresql://db-postgres:5432/lista_presenca"
            - name: DB_USER
              value: "regis"
            
            # --- O Pulo do Gato para o Spring ler o Vault ---
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/vault/secrets/database.properties"
              
            # --- Dieta da Memória ---
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseSerialGC -Xmx128m -Xms64m -XX:MaxMetaspaceSize=96m -Xss256k"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
              value: "1"
            - name: SPRING_MAIN_LAZY_INITIALIZATION
              value: "true"
            - name: SPRING_JPA_OPEN_IN_VIEW
              value: "false"
            - name: SPRING_JMX_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: lista-presenca-backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP